<!--
 * COPYRIGHT (C) 2010
 * RE2, INC.
 *
 * Author: RE2
 *
 * This file is a part of RobotModel, which was developed for the
 * DARPA ARM ROBOT Track C project.
 *
 * RobotModel is free software:
 * you can redistribute it and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation, either version
 * 3 of the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License along
 * with this package.  If not, see <http://www.gnu.org/licenses/>.
 *
 * RE2, INC. disclaims all warranties with regard to this software, including
 * all implied warranties of merchantability and fitness, in no event shall
 * RE2, INC. be liable for any special, indirect or consequential damages or
 * any damages whatsoever resulting from loss of use, data or profits, whether
 * in an action of contract, negligence or other tortious action, arising out
 * of or in connection with the use or performance of this software.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- <xacro:include filename="$(find wam_model)/models/hand.urdf.xacro"/> -->
  <xacro:include filename="$(find wam_model)/models/common.urdf.xacro"/>
  <xacro:property name="b" value=".5"/>

  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Tennis Net -->
  <!-- <xacro:macro name="tennis_net" params="parent_link" >
    <joint name="net_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="net_link"/>
      <origin xyz="11.885 0 0.535" rpy="0 0 0"/>
    </joint>
    <link name="net_link">
      <visual>
          <material name="White">
            <color rgba="1 1 1 0.9"/>
          </material>
          <origin xyz="0 6.4 -0.535" rpy="${PI/2} 0 ${-PI/2}" />
          <geometry>
            <mesh filename="${models_path}/sw_meshes/net_4.STL" scale="0.001 0.001 0.001"/>
          </geometry>
        </visual>
    </link>
  </xacro:macro> -->

  <!-- Upper arm macros -->
  <xacro:macro name="wam_base" params="prefix parent_link xyz rpy">

    <joint name="${prefix}/wam_fixed_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${prefix}/base_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <gazebo reference="${prefix}/base_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name = "${prefix}/base_link">
      <inertial>
        <origin xyz="0.1 0 0" />
        <mass value=".1" />
        <inertia
          ixx="0.1" ixy="0"   ixz="0"
                  iyy="0.1"   iyz="0"
                            izz="0.1" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 0.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/base_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/base_link_convex.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_shoulder_yaw" params="prefix">
    <joint name="${prefix}/base_yaw_joint" type="revolute">
      <parent link="${prefix}/base_link"/>
      <child link="${prefix}/shoulder_yaw_link"/>
      <origin xyz="0 0 0.346" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="53" lower="-2.6" upper="2.6" velocity="10.0"/>
      <dynamics damping="${1.8*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/base_yaw_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/base_yaw"/>

    <gazebo reference="${prefix}/shoulder_yaw_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/shoulder_yaw_link" >
      <inertial>
        <origin xyz="-.00443422 -.00066489 -0.1289039 " />
        <mass value="0.0001" />
        <inertia
          ixx=".13488033"  ixy="-0.00012485"   ixz="0.00213041"
                           iyy=".09046330"    iyz="-.00068555"
                                              izz=".11328369" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/shoulder_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/shoulder_link_convex_decomposition.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_shoulder_pitch" params="prefix">
    <joint name="${prefix}/shoulder_pitch_joint" type="revolute">
      <parent link="${prefix}/shoulder_yaw_link"/>
      <child link="${prefix}/shoulder_pitch_link"/>
      <origin xyz="0 0 0" rpy="${-PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="53" lower="-2" upper="2" velocity="10"/>
      <dynamics damping="${0.5*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/shoulder_pitch_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/shoulder_pitch"/>

    <gazebo reference="${prefix}/shoulder_pitch_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/shoulder_pitch_link" >
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/shoulder_pitch_link_fine.stl"/>
        </geometry>
      </visual>
      <inertial>
        <origin xyz="-.00236981 -.01542114 .03105614 " />
        <mass value="0.0001" />
        <inertia
          ixx="0.02140958"  ixy="-0.00002461"  ixz="0.00027172"
                            iyy="0.015589060"  iyz="0.0018192"
                                               izz="0.01377875" />
      </inertial>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/shoulder_pitch_link_convex.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_upper_arm" params="prefix">
    <joint name="${prefix}/shoulder_yaw_joint" type="revolute">
      <parent link="${prefix}/shoulder_pitch_link"/>
      <child link="${prefix}/upper_arm_link"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="45" lower="-2.8" upper="2.8" velocity="10"/>
      <dynamics damping="${1.5*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/shoulder_yaw_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/shoulder_yaw"/>

    <gazebo reference="${prefix}/upper_arm_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/upper_arm_link" >
      <inertial>
        <origin xyz="0.00683258580000000 0.000033090000000 0.392492300000000" />
        <mass value="0.0001" />
        <inertia
          ixx=".05911077"  ixy="-0.00000738"  ixz="-0.00249612"
                           iyy="0.05927043"   iyz="0.00001767"
                                              izz="0.0032455" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/upper_arm_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/upper_arm_link_convex_decomposition.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Forearm macros -->
  <xacro:macro name="wam_forearm" params="prefix">
    <joint name="${prefix}/elbow_pitch_joint" type="revolute">
      <parent link="${prefix}/upper_arm_link"/>
      <child link="${prefix}/forearm_link"/>
      <origin xyz="0.045 0 0.55" rpy="${-PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="30" lower="-0.9" upper="${PI + .2}" velocity="10"/>
      <dynamics damping="${0.8*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/elbow_pitch_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/elbow_pitch"/>

    <gazebo reference="${prefix}/forearm_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/forearm_link" >
      <inertial>
        <mass value="0.0001" />
        <origin xyz="-0.04001488 -.14271662 -.00022942 " rpy="0 0 0" />
        <inertia
          ixx="0.01491672" ixy="0.001506040000000" ixz="0.000017410000000"
                           iyy="0.002944630000000" iyz="0.000021090000000"
                                                   izz="0.014829880000000" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/elbow_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/elbow_link_convex.dae"/>
        </geometry>
      </collision>

      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <origin xyz="-0.045 -0.0730 0" rpy="${PI/2} 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/forearm_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.045 -0.0730 0" rpy="${PI/2} 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/forearm_link_convex_decomposition.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_wrist_yaw" params="prefix">
    <joint name="${prefix}/wrist_yaw_joint" type="revolute">
      <parent link="${prefix}/forearm_link"/>
      <child link="${prefix}/wrist_yaw_link"/>
      <origin xyz="-0.045 -0.3 0" rpy="${PI/2} ${PI} 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="10" lower="-4.55" upper="1.35" velocity="10"/>
      <dynamics damping="${0.5*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/wrist_yaw_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/wrist_yaw"/>

    <gazebo reference="${prefix}/wrist_yaw_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/wrist_yaw_link" >
      <inertial>
        <origin xyz="0.00008921 0.00435824 -0.00511217 " />
        <mass value="0.0001" />
        <inertia  ixx="0.00005029" ixy="0.00000020"  ixz="0.00007582"
          iyy="0.00007582"  iyz="-0.00000359"
          izz="0.00006270" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_yaw_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_yaw_link_convex_decomposition.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_wrist_pitch" params="prefix">
    <joint name="${prefix}/wrist_pitch_joint" type="revolute">
      <parent link="${prefix}/wrist_yaw_link"/>
      <child link="${prefix}/wrist_pitch_link"/>
      <origin xyz="0 0 0" rpy="${-PI/2} 0 ${PI}"/>
      <axis xyz="0 0 1"/>
      <limit effort="10" lower="-1.5707" upper="1.5707" velocity="10"/>
      <dynamics damping="${0.1*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/wrist_pitch_joint">
      <xacro:gz_joint/>
    </gazebo>
  <xacro:transmission prefix="${prefix}/wrist_pitch"/>

  <gazebo reference="${prefix}/wrist_pitch_link">
    <material>Gazebo/Grey</material>
  </gazebo>

    <link name="${prefix}/wrist_pitch_link" >
      <inertial>
        <origin xyz="-0.00012262 -0.02468336 -0.01703194 " rpy="0 0 0" />
        <mass value="0.0001" />
        <inertia
          ixx="0.00055516"  ixy="0.00000061"  ixz="-0.00000074"
          iyy="0.00024367"  iyz="-0.00004590"
          izz="0.00045358" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_pitch_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_pitch_link_convex_decomposition.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Palm without force-torque sensor -->
  <xacro:macro name="wam_palm" params="prefix">
    <joint name="${prefix}/palm_yaw_joint" type="revolute">
      <parent link="${prefix}/wrist_pitch_link"/>
      <child link="${prefix}/wrist_palm_link"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="10" lower="-2.95" upper="2.95" velocity="10"/>
      <dynamics damping="${0.1*b}" friction="0"/>
    </joint>
    <gazebo reference="${prefix}/palm_yaw_joint">
      <xacro:gz_joint/>
    </gazebo>
    <xacro:transmission prefix="${prefix}/palm_yaw"/>

    <gazebo reference="${prefix}/wrist_palm_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/wrist_palm_link" >
      <inertial>
        <origin xyz="0.0 0.0 0.055" rpy="0 0 0" />
        <mass value="0.0001" />
        <inertia  ixx="0.00010859" ixy="0.00000000"  ixz="-0.00000000"
          iyy="0.00020683"  iyz="-0.0000000"
          izz="0.00010851" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_palm_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wrist_palm_link_convex.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="wam_wrist_palm_stump" params="prefix">
    <joint name="${prefix}/wrist_palm_stump_joint" type="fixed">
      <parent link="${prefix}/wrist_palm_link"/>
      <child link="${prefix}/wrist_palm_stump_link"/>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}/wrist_palm_stump_link" >
      <inertial>
        <mass value="0.000001" />
        <inertia
          ixx="0.0000001" ixy="0.0" ixz="0.0"
          iyy="0.0000001" iyz="0.0"
          izz="0.0000001" />
      </inertial>
    </link>
  </xacro:macro>

  <!-- Raquet -->
  <xacro:macro name="racquet" params="prefix">
      <joint name="${prefix}/racquet_joint" type="fixed">
      <parent link="${prefix}/wrist_palm_stump_link"/>
      <child link="${prefix}/racquet_link"/>

      <!-- for racket head in straight position -->
      <!-- <origin xyz="0 0 0.01" rpy="0 0 0"/> -->

      <!-- for racket head in perpendicular starting position -->
      <origin xyz="0 0 0.01" rpy="0 0 ${PI/2}"/>
    </joint>

    <gazebo reference="${prefix}/racquet_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}/racquet_link" >
      <inertial>
       <mass value="0.00001"/>
       <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
      <visual>
        <material name="Yellow">
          <color rgba="1.0 1.0 0.0 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/racket_new.stl" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/racket_new.stl" scale="1 1 1"/>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}/racquet_hitpoint_link"/>
      <joint name="${prefix}/racquet_hitpoint_joint" type="fixed">
        <parent link="${prefix}/racquet_link"/>
        <child link="${prefix}/racquet_hitpoint_link"/>
        <origin xyz="0 0 0.520" rpy="0 ${PI/2} 0"/>
    </joint>
  </xacro:macro>

    <!-- Wheelchair -->
  <xacro:macro name="wheelchair" params="prefix">
      <joint name="${prefix}/wheelchair_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}/wheelchair_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}/wheelchair_link" >
      <inertial>
        <origin xyz="0.0 0.0 0" rpy="0 0 0" />
        <mass value="10" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
      <visual>
        <!-- <material name="TealBlue"> -->
        <material name="Gray">
          <color rgba="0.7 0.7 0.7 1.0"/>
          <!-- <color rgba="0.212 0.459 0.533 1.0"/> -->
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wheelchair_cad.stl" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/wheelchair_cad.stl" scale="1 1 1"/>
        </geometry>
        <surface>
        <friction>
          <ode>
            <mu>1</mu>
            <mu2>1</mu2>
          </ode>
        </friction>
      </surface>
      </collision>
    </link>
    <gazebo reference="${prefix}/wheelchair_link">
      <turnGravityOff>0</turnGravityOff>
      <material>Gazebo/Grey</material>
    </gazebo>

  </xacro:macro>

  <!-- SICK LiDAR -->
  <!-- <xacro:macro name="lidar" params="prefix">
    <link name="${prefix}/lidar_link" />
    <joint name="${prefix}/lidar_joint" type="fixed">
      <parent link="${prefix}/wheelchair_link"/>
      <child link="${prefix}/lidar_link"/>
      <origin xyz="0.2709589 0 -0.0866" rpy="0 0 0"/>
    </joint>
  </xacro:macro> -->

  <!-- Velodyne LiDAR Mount -->
  <xacro:macro name="lidar_mount" params="prefix">
    <joint name="lidar_mount_joint" type="fixed">
      <parent link="${prefix}/wheelchair_link"/>
      <child link="lidar_mount_link"/>
      <origin xyz="0.19739 0 -0.10835" rpy="0 0 0"/>
    </joint>
    <link name="lidar_mount_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="Black">
          <color rgba="0.0 0.0 0.0 1.0" />
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/vlp16_mount.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${models_path}/sw_meshes/vlp16_mount.stl" scale="0.0009 0.0009 0.0009"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Velodyne LiDAR VLP16 -->
  <xacro:macro name="lidar" >
    <joint name="lidar_joint" type="fixed">
      <parent link="lidar_mount_link"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="lidar_link">
      <visual>
          <material name="Blue">
            <color rgba="0.1725 0.1059 0.7019 1.0"/>
          </material>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="${models_path}/sw_meshes/vlp_16.stl" scale="0.001 0.001 0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0.001" rpy="0 0 0" />
          <geometry>
            <mesh filename="${models_path}/sw_meshes/vlp_16.stl" scale="0.0009 0.0009 0.0009"/>
          </geometry>
        </collision>
    </link>
  </xacro:macro>

     <!--Zed on Wheelchair-->
  <xacro:macro name="zed_wheelchair" params="prefix name">

    <xacro:include filename="$(find ball_calibration)/models/include/materials.urdf.xacro" />
    <xacro:property name="M_PI"     value="3.1415926535897931" />

    <xacro:property name="baseline" value="0.12" />
    <xacro:property name="height" value="0.030" />
    <xacro:property name="bottom_slope" value="0.05" />
    <xacro:property name="screw_offset_x" value="0.0" />
    <xacro:property name="optical_offset_x" value="-0.01" />

    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="${name}_base_link" />
    <joint name="${name}_base_joint" type="fixed">
      <parent link="${prefix}/wheelchair_link"/>
      <child link="${name}_base_link"/>
      <origin xyz="0.3333589 0 0" rpy="0 0 0"/>
    </joint>


    <!-- Camera Center -->
    <link name="${name}_camera_center">
      <visual>
        <origin xyz="${screw_offset_x} 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ball_calibration/models/models/zed2.stl"  scale="1 1 1" />
        </geometry>
        <material name="zed2_mat" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ball_calibration/models/models/zed2.stl"  scale="0.92 0.92 0.92" />
        </geometry>
      </collision>
    </link>
    <joint name="${name}_camera_center_joint" type="fixed">
      <parent link="${name}_base_link"/>
      <child link="${name}_camera_center"/>
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>


    <!-- Left Camera -->
    <link name="${name}_left_camera_frame" />
    <joint name="${name}_left_camera_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_left_camera_frame"/>
      <origin xyz="0 ${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_left_camera_optical_frame"/>
    <joint name="${name}_left_camera_optical_joint" type="fixed">
      <origin xyz="${optical_offset_x} 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${name}_left_camera_frame"/>
      <child link="${name}_left_camera_optical_frame"/>
    </joint>


    <!-- Right Camera -->
    <link name="${name}_right_camera_frame" />
    <joint name="${name}_right_camera_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_right_camera_frame"/>
      <origin xyz="0 -${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_right_camera_optical_frame"/>
    <joint name="${name}_right_camera_optical_joint" type="fixed">
      <origin xyz="${optical_offset_x} 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${name}_right_camera_frame"/>
      <child link="${name}_right_camera_optical_frame"/>
    </joint>


    <!-- ZED2 Sensors -->
    <link name="${name}_imu_link" />
    <joint name="${name}_imu_link_joint" type="fixed">
     <parent link="${name}_left_camera_frame"/>
     <child link="${name}_imu_link"/>
     <origin xyz="-0.002 -0.023 -0.002" rpy="0.00138 -0.00116 -0.00176" />
    </joint>

    <link name="${name}_mag_link" />
    <joint name="${name}_mag_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_mag_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_baro_link" />
    <joint name="${name}_baro_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_baro_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_temp_left_link" />
    <joint name="${name}_temp_left_joint" type="fixed">
      <parent link="${name}_left_camera_frame"/>
      <child link="${name}_temp_left_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_temp_right_link" />
    <joint name="${name}_temp_right_joint" type="fixed">
      <parent link="${name}_right_camera_frame"/>
      <child link="${name}_temp_right_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

  </xacro:macro>

      <!-- Wheelchair Rollers -->
  <!-- <xacro:macro name="wheelchair_roller" params="prefix name xyz">
    <joint name="${prefix}/${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}/${name}_link"/>
      <origin xyz="${xyz}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${prefix}/${name}_link" >
        <inertial>
        <mass value="1"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
      <visual>
        <geometry>
           <cylinder length="0.01" radius="0.03"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.03"/>
        </geometry>
        <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
          </ode>
        </friction>
      </surface>
      </collision>
    </link>
    <xacro:effort_transmission prefix="${prefix}/${name}"/>
  </xacro:macro>

  <xacro:macro name="wheelchair_rollers" params="prefix">
    <xacro:wheelchair_roller prefix="${prefix}" name="FL_roller" xyz=" 0.18  0.26 -0.44"/>
    <xacro:wheelchair_roller prefix="${prefix}" name="FR_roller" xyz=" 0.18 -0.26 -0.44"/>
    <xacro:wheelchair_roller prefix="${prefix}" name="BC_roller" xyz="-0.39     0 -0.43"/>
  </xacro:macro> -->

  <!-- Wheelchair Wheels -->
  <!-- <xacro:macro name="wheelchair_wheel" params="prefix name xyz rpy">
    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="4"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
      <visual>
        <geometry>
           <cylinder length="0.01" radius="0.25"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.01" radius="0.25"/>
        </geometry>
        <surface>
        <friction>
          <ode>
            <mu>1</mu>
            <mu2>1</mu2>
          </ode>
        </friction>
      </surface>
      </collision>
    </link>
    <xacro:effort_transmission prefix="${prefix}/${name}"/>
  </xacro:macro> -->

  <!-- <xacro:macro name="wheelchair_wheels" params="prefix">
    <xacro:wheelchair_wheel prefix="${prefix}" name="wheel_right" xyz="-0.12 -0.5 -0.22" rpy="${-PI/2}  0.0 0.0"/>
    <xacro:wheelchair_wheel prefix="${prefix}" name="wheel_left" xyz="-0.12  0.5 -0.22" rpy="${-PI/2}  0.0 0.0"/>

  </xacro:macro> -->

  <!-- Hollow forearm macros -->
  <!--<xacro:macro name="wam_hollow_forearm" params="prefix">-->
    <!--<joint name="${prefix}/elbow_joint" type="revolute">-->
      <!--<parent link="${prefix}/upper_arm_link"/>-->
      <!--<child link="${prefix}/forearm_link"/>-->
      <!--<origin xyz="0.045 -0.55 0" rpy="${0.5 * PI} 0 0"/>-->
      <!--<axis xyz="0 1 0"/>-->
      <!--<limit effort="15" lower="-0.9" upper="${PI}" velocity="0.50"/>-->
      <!--[> <safety_controller k_position="100" k_velocity="3" soft_lower_limit="-100.0" soft_upper_limit="100.0" /> <]-->
      <!--<dynamics damping="0.1" friction="100.0"/>-->
    <!--</joint>-->
    <!--<link name="${prefix}/forearm_link" >-->
      <!--<inertial>-->
        <!--<origin xyz="0 0 0" />-->
        <!--<mass value="3.20016804" />-->
        <!--<origin xyz="-0.04001488 -.00022942 .13271662" rpy="0 0 0" />-->
        <!--<inertia  ixx="0.01491672" ixy="0.00001741"   ixz="-0.00150604"-->
          <!--iyy="0.01482988"   iyz="-0.00002109"-->
          <!--izz="0.00294463" />-->
      <!--</inertial>-->
      <!--<visual>-->
        <!--<material name="WAMGrey">-->
          <!--<color rgba="0.7 0.7 0.7 1.0"/>-->
        <!--</material>-->
        <!--<origin xyz="0 0 0" rpy="-${PI} 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/wamForeArmLink4.DAE"/>-->
        <!--</geometry>-->
      <!--</visual>-->
      <!--<collision>-->
        <!--<origin xyz="0 0 0" rpy="-${PI} 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/wamForeArmLink4.stl"/>-->
        <!--</geometry>-->
      <!--</collision>-->
    <!--</link>-->
  <!--</xacro:macro>-->

  <!--<xacro:macro name="wam_hollow_wrist" params="prefix">-->
    <!--<joint name="${prefix}/UpperWristJoint" type="fixed">-->
      <!--<parent link="${prefix}/ForeArmLink"/>-->
      <!--<child link="${prefix}/LowerWristPalmLink"/>-->
      <!--<origin xyz="-0.045 0 .35" rpy="-${0.5 * PI} 0 ${0.5 * PI}"/>-->
      <!--<axis xyz="0 -1 0"/>-->
      <!--<limit effort="5" lower="-4.8" upper="1.3" velocity="0.20"/>-->
      <!--[> <safety_controller k_position="100" k_velocity="3" soft_lower_limit="-100.0" soft_upper_limit="100.0" /> <]-->
      <!--<dynamics damping="0.1" friction="100.0"/>-->
    <!--</joint>-->
    <!--<link name="${prefix}/LowerWristPalmLink" >-->
      <!--<inertial>-->
        <!--<origin xyz="0.00008921 0.00511217 0.00435824" />-->
        <!--<mass value="1.12376019" />-->
        <!--<inertia  ixx="0.00005029" ixy="0.00000020"  ixz="0.00007582"-->
          <!--iyy="0.00007582"  iyz="-0.00000359"-->
          <!--izz="0.00006270" />-->
      <!--</inertial>-->
      <!--<visual>-->
        <!--<material name="WAMGrey">-->
          <!--<color rgba="0.7 0.7 0.7 1.0"/>-->
        <!--</material>-->
        <!--<origin xyz="0 0.02711 0" rpy="${PI} 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/wamUpperWristYawLink.DAE"/>-->
        <!--</geometry>-->
      <!--</visual>-->
      <!--<collision>-->
        <!--<origin xyz="0 0.02711 0" rpy="${PI} 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/wamUpperWristYawLink5.stl"/>-->
        <!--</geometry>-->
      <!--</collision>-->
    <!--</link>-->
  <!--</xacro:macro>-->

  <!-- Palm with ForceTorque macros -->
  <!--<xacro:macro name="LowerWristFT" params="prefix">-->
    <!--<joint name="${prefix}/LowerWristYawJoint" type="revolute">-->
      <!--<parent link="${prefix}/UpperWristPitchLink"/>-->
      <!--<child link="${prefix}/LowerWristYawLink"/>-->
      <!--<origin xyz="0 0 0.06713340" rpy="0 0 0"/>-->
      <!--<axis xyz="0 0 1"/>-->
      <!--<limit effort="5" lower="-2.95" upper="2.95" velocity="0.20"/>[> 2.95 is a limit taken in from 3 due to saftey and differences between arms. <]-->
      <!--[> <safety_controller k_position="100" k_velocity="3" soft_lower_limit="-100.0" soft_upper_limit="100.0" /> <]-->
      <!--<dynamics damping="0.1" friction="100.0"/>-->
    <!--</joint>-->
    <!--<link name="${prefix}/LowerWristYawLink" >-->
      <!--<inertial>-->
        <!--<origin xyz="-0.00000134 -0.00228167 -0.00000141" rpy="0 0 0" />-->
        <!--<mass value="0.17286134" />-->
        <!--<inertia  ixx="0.00010859" ixy="0.00000000"  ixz="-0.00000000"-->
          <!--iyy="0.00020683"  iyz="-0.0000000"-->
          <!--izz="0.00010851" />-->
      <!--</inertial>-->
      <!--<visual>-->
        <!--<material name="WAMGrey">-->
          <!--<color rgba="0.7 0.7 0.7 1.0"/>-->
        <!--</material>-->
        <!--<origin xyz="0 0 0" rpy="0 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/forceTorqueSensor.DAE"/>-->
        <!--</geometry>-->
      <!--</visual>-->
      <!--<collision>-->
        <!--<origin xyz="0 0 0" rpy="0 0 0" />-->
        <!--<geometry>-->
          <!--<mesh filename="${models_path}/meshes/forceTorqueSensor.stl"/>-->
        <!--</geometry>-->
      <!--</collision>-->
    <!--</link>-->
  <!--</xacro:macro>-->

  <xacro:macro name="wam_stump" params="prefix">
    <joint name="${prefix}/elbow_pitch_joint" type="revolute">
      <parent link="${prefix}/upper_arm_link"/>
      <child link="${prefix}/stump_link"/>
      <origin xyz="0.045 0 0.55" rpy="${-PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" lower="${-pi}" upper="${pi}" velocity="100"/>
      <dynamics damping="${0.1*b}" friction="0"/>
    </joint>
    <link name="${prefix}/stump_link" >
      <inertial>
        <mass value="0.0001" />
        <origin xyz="-0.0195 -.02566 -.00022942 " rpy="0 0 0" />
        <inertia
          ixx="0.01491672" ixy="0.001506040000000" ixz="0.000017410000000"
                           iyy="0.002944630000000" iyz="0.000021090000000"
                                                   izz="0.014829880000000" />
      </inertial>
      <visual>
        <material name="WAMGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/elbow_link_fine.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="${models_path}/sw_meshes/elbow_link_convex.dae"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>
</robot>
