#robot_localization EKF configuration from zed and wheel odometry data

frequency: 100
#sensor_timeout: 0
two_d_mode: true

map_frame: map
odom_frame: odom
world_frame: odom  # odom -> robot mode
base_link_frame: base_footprint

# # #(X,Y,Z,roll,pitch,yaw,X˙,Y˙,Z˙,roll˙,pitch˙,yaw˙,X¨,Y¨,Z¨)
# imu0: /imu
# imu0_config: [false, false, false,
#              false, false, true,
#              false, false, false,
#              false, false, true,
#              false, false, false]
# imu0_queue_size: 100
# imu0_differential: false #true
# imu0_relative: true

imu0: /zed_wheelchair_node/imu/data
imu0_config: [false, false, false,
             false, false, true,
             false, false, false,
             false, false, true,
             false, false, false]
imu0_queue_size: 100
imu0_differential: true
imu0_relative: true

odom0: /wheelchair/drive_controller/odom # Only care about x, y, yaw (rest should be constant)
odom0_config: [false,  false,  false,
               false, false, false,
               true, false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 100
odom0_nodelay: true
odom0_relative: true

publish_tf: true