joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "wheel_left_joint"
  right_wheel: "wheel_right_joint"
  pose_covariance_diagonal: []
  twist_covariance_diagonal: []

  # outer to outer: 94.3, inner to inner: 1.85 to 92.7= 90.85, wheel thickness 16-25 mm
  wheel_separation: 0.92575 #0.92575 #0.8937625  #0.9085
  wheel_radius: 0.319 #0.322 #0.31860236 #0.3225

  base_frame_id: base_footprint
  odom_frame_id: odom
  enable_odom_tf: false

  publish_rate: 200

  velocity_rolling_window_size: 1

  publish_cmd: True

  linear:
    x:
      has_velocity_limits: true
      max_velocity: 3 #5 # m/s
      min_velocity: -3 #-5 # m/s
      has_acceleration_limits: true
      max_acceleration: 2.5 #2.5 # m/s^2 (ODrive: 40 units?)
      min_acceleration: -2.5 #-2.5 # m/s^2 (ODrive: 40 units?)
      has_jerk_limits: false
      # max_jerk: 0.5 #5.0  # m/s^3

  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2 #5 # rad/s
      has_acceleration_limits: true
      max_acceleration: 1 #1.5 #5 # rad/s^2

#pid_0: {p: 1, d: 0.0}
#pid_1: {p: 1, d: 0.0}
