DWAPlannerROS:

  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 3.2

  max_vel_trans: 5
  min_vel_trans: -5

  max_vel_x: 5
  min_vel_x: -5
  max_vel_y: 0
  min_vel_y: -0

  max_rot_vel: 6.0
  min_rot_vel: -6.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 20.0

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

  oscillation_reset_dist: 0.05

  prune_plan: true


TrajectoryPlannerROS:
  max_vel_x: 20
  min_vel_x: -20
  max_vel_theta: 20
  min_in_place_vel_theta: 20

  acc_lim_theta: 10
  acc_lim_x: 20
  acc_lim_y: 20

  holonomic_robot: false