local_costmap:
  update_frequency: 25.0
  publish_frequency: 25.0
  rolling_window: true
  width: 25
  height: 25

  transform_tolerance: 0.2
  robot_radius: 0.65

  always_send_full_costmap: false
  static_map: false

  plugins:
     - {name: "map_server", type: "costmap_2d::StaticLayer"}
     - {name: "obstacles", type: "costmap_2d::ObstacleLayer"}
     - {name: "inflation", type: "costmap_2d::InflationLayer"}

  map_server:
    map_topic: "/borders/map"

  obstacles:
        combination_method: 0
        observation_sources: laser
        track_unknown_space: false
        laser:
            data_type: PointCloud2
            topic: /velodyne_points
            frame_name: lidar_link
            expected_update_rate: 0
            observation_persistence: 0.0
            marking: true
            clearing: true
            obstacle_range: 9999
            min_obstacle_height: 0.1

  inflation:
    inflation_radius: 0.2
    cost_scaling_factor: 10
